export { default as Login } from './Login';
export { default as FoodsPage } from './Home/FoodsPage';
export { default as DrinksPage } from './Home/DrinksPage';
export { default as RecipeInProgress } from './RecipeInProgress';
export { default as ExploreRecipes } from './ExplorarBebidasComidas';
export { default as Explore } from './ExplorarGeral';
export { default as ExploreIngredient } from './ExploreIngredient';
export { default as FavoriteRecipes } from './FavoriteRecipes';
export { default as NotFound } from './NotFound';
